apiVersion: v1
kind: Service
metadata:
  name: uki-bi-app-2-svc
  labels:
    app: uki-bi-app-2
spec:
  type: ClusterIP
  selector:
    app: uki-bi-app-2
  ports:
  - name: uki-bi-app-2-svc-port
    port: 8080
    protocol: TCP
    targetPort: 8080
